### PR TITLE
0.6 compatibility

### PR DESCRIPTION
**Pull request by mmalecki**
Main changes:
- removed references to mutable `require.paths`,
- replaced/removed references to `sys`,
- made the example work,
- a bit of refactoring (unused `require`s).

Test and example still work on `node v0.4.12`.

### CODE REVIEW

**Comment by mbseid** [comment]
Thanks for this patch.  Quick question, what version of Node.JS is Journey intended for now?  Can't find it anywhere.

**Comment by mmalecki** [comment]
It works perfectly on `node <= v0.4`, but fails on anything newer than that (`node v0.5.x` and `node v0.6.x`).

**Comment by mbseid** [comment]
Weird, Cause I was trying it with Node version 0.4.7 and it still wasn't working.  Might have been my environment. O well.

Anyways, I have been woking with your updated branch,  `mmalecki:0.6-compatibility` and everything has been working as expected.  Thanks for updating the module!

**Comment by obazoud** [comment]
Is there any chance to release and deploy Journey with this pull request ?

**Comment by nekaab** [comment]
+1

**Comment by indexzero** [comment]
done

**Comment by nekaab** [comment]
awesome, thanks!

**Comment by obazoud** [comment]
thanks!

**Pull request merged**
